// <auto-generated />
namespace CompletedDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class TweakSPROC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TweakSPROC));
        
        string IMigrationMetadata.Id
        {
            get { return "201402111821286_TweakSPROC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
